### ISSUE TITLE
7. Events landing page

### ISSUE THREAD

**Issue by murphybarb** [BCcampus/bcc-sage#142]

**Comment by alex-418** [comment]
@completed via #181 @murphybarb I've created the "Events" page on Helga, note that it needs the template "Events Landing Page" assigned, and the calendar short-code in the content body. I've also gone ahead and created two event categories: edtech an flo. Assigning an event to one of these categories will make them show up in the corresponding list on the events landing page. https://helga.bccampus.ca/wp/bcc/events/

**Comment by alex-418** [comment]
@murphybarb sorry about that, looks like the category got over-written, both were pulling from edtech. I've fix that, and also an issue with the links going to the events page instead of the specific event. Also, not sure if it's just my browser but the height of the FLO image div is taller for me, and the purple title doesn't quite cover 100% of that, will have to address in styling if that's the case. (some last minute change we made today must've caused this)

**Comment by murphybarb** [comment]
@alex-418, thanks!

I can't view the site as I'm outside the BCcampus office IP address. I looked closely at it last night and all seemed ok, with the exception of the tagging issue I mentioned above. so I will move to 'done'

Looking at the events landing page made me realize the functionality of the events section is not working properly. I will send an email to you and Brad

**Comment by murphybarb** [comment]
@bdolor 
This was moved to "done" but is still not working correctly. I'm moving back to "doing". See the area at the bottom of the page "EdTech Demos" and "Facilitating Learning Online"

Events you tag with "EdTech" show up under "Facilitating Learning Online" and the opposite happens with events you tag with "FLO", they show up under "EdTech Demos"

**Comment by bdolor** [comment]
should be fixed via https://github.com/BCcampus/bcc-sage/commit/0b4ceaabad4dea44657e30cd2292dd14ce74f2fb
