### ISSUE TITLE
8. Events content page

### ISSUE THREAD

**Issue by murphybarb** [BCcampus/bcc-sage#143]

**Comment by alex-418** [comment]
@murphybarb Had a lot of questions about this one. I applied some styling via #195 to get closer to the design, but was not comfortable with removing the following functionality that seems helpful without confirming that it wasn't overlooked: 
- "add to calendar" on the right-hand side 
- event taxonomy (categories, tags) at the bottom of event details section 
-  tag that signals if it's an all-day event
- "calendar" on the right-hand site 
- email link in contact
- event website link 

If the desired behavior is to remove all of this functionality, it'll add significant overhead because the plugin only lets us modify this by creating a child theme in the plugin directory itself, not in our theme. [Details of that.](https://time.ly/resources/additional-wordpress-settings/advanced-settings-for-your-timely-wordpress-calendar/create-new-calendar-theme/) This is not ideal, because we do not version control (in GitHub) plugin files, therefore it's not part of our deployment workflow. The impact of this means a manual process to get our new "plugin theme" files onto cert and prod. 

Event images: 
I did not add the image to the event as per design, the reason being when I looked at existing events images, they were not the appropriate size/aspect ratio. They are mostly banners or smaller images. This would not work with the design on single event pages, or for the featured event image as well across the site. For example, the single event page requires an image with a fixed height/width and be 50% of the event containers horizontal width. This is also not ideal due to the varying image dimensions, and height of the event container changing, depending on how many of the event details are filled out. Hope that makes sense... hope to get back or find an option that would work well with varying image sizes, and varying event details (which impacts the height of the div).

**Comment by alex-418** [comment]
@stargraphicdesign please see my comment above

**Comment by stargraphicdesign** [comment]
I can't find any working pages to look at re:this

Also I'm assuming that you just meant you wanted me to comment on the image thing. 

I planned a lot of my images on the site to utilize a background-cover, flexing and cropping to their space. The images for events will accommodate this new design going forward so i'm not worried about old content, and a set of default images has been chosen for any event that the user doesn't have a photo available for.

**Comment by alex-418** [comment]
@ehbeattie Confirmed that we are ignoring the mockup which removes essential functionality.
