### ISSUE TITLE
child page display (to be used throughout theme) 

### ISSUE THREAD

**Issue by alex-418** [BCcampus/bcc-sage#166]
## Submit a feature request or bug report

- [x] This is a feature request
- [ ] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

## Feature Request
Create a short-code that takes 3 attributes: Parent, Limit, Display option(image, date, etc). The output will be a list of the child pages.

**Comment by bdolor** [comment]
research https://wordpress.org/plugins/cc-child-pages/ to see if it has potential

**Comment by bdolor** [comment]
using custom functions and markup instead of shortcode or a plugin that doesn't meet our needs. 

- https://github.com/BCcampus/bcc-sage/blob/dev/app/controllers/Page.php#L15
- https://github.com/BCcampus/bcc-sage/blob/dev/app/controllers/App.php#L265

can be validated on various pages...looking at whether they display the child pages of a parent page. 
- https://helga.bccampus.ca/wp/bcc/
- https://helga.bccampus.ca/wp/bcc/projects/ 
- https://helga.bccampus.ca/wp/bcc/topics-of-practice/

**Comment by murphybarb** [comment]
Hey @bdolor, I'm not 100% what I'm validating on this one. Can you provide some deets on what I'm looking at specifically at the URLs indicated above. Thanks for being awesome!
