### ISSUE TITLE
Performance Improvements

### ISSUE THREAD

**Issue by bdolor** [BCcampus/bcc-sage#219]
## Submit a feature request or bug report

- [ ] This is a feature request
- [x] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**

Lighthouse Labs audit reveals an extremely substandard score for performance. 

![image](https://user-images.githubusercontent.com/2048170/46556221-d773a800-c89a-11e8-9387-5ea555f74548.png)

**What is the expected or desired behavior?**

Performance measures of the site need to be brought up to a minimum level of greater than 50

**Comment by alex-418** [comment]
The majority of improvements turned out to be around images, images on production are very large. These are images that have been uploaded through Wordpress as either a Featured image to an Event or Page, and/or are in-line images in the content. There is about >2000 of them, so manually optimizing and updating each event/page wasn't a good solution. We need something that will optimize existing ones without having to update each event/pages featured image, and also optimize future images when they are uploaded.

![performance](https://user-images.githubusercontent.com/17072191/51771730-d14e4500-209e-11e9-903e-8ff6fabde7b7.png)

I explored a few plugins that could save us this headache, all required an account and API to use their service, but I [found one](https://en-ca.wordpress.org/plugins/wp-smushit/) that doesn't (although it doesn't compress as best as it could). 

I've installed and testing this on production... it's painfully slow and somewhat manual, and not compression the images as much as they could be as i'm on the free version. Would like to request this image compression/optimization problem be made into its own issue, so we can have the time to find and test a good solution. I will be removing this plugin from production once it has compressed the images.

**Comment by bdolor** [comment]
> Would like to request this image compression/optimization problem be made into its own issue

do it

**Comment by ehbeattie** [comment]
Yeah, what Brad said.

**Comment by alex-418** [comment]
Done. Please see #318

**Comment by alex-418** [comment]
It looks like the maximum image size plugin could smush was <1 mb so that leaves out the large ones. 
It gave out on production after 20mb reduced... I've now removed it.

![smush](https://user-images.githubusercontent.com/17072191/51774780-54c06400-20a8-11e9-9e58-f9f9a1b9b457.png)

**Comment by dshaykewich** [comment]
@alex-418 , @ehbeattie , would love to tackle this one in the sprint.  There are a few very fast (*insert laugh track*) fixes to speed things up by sizing/formatting images appropriately.  This image is bigger than a MB and is presented in thumbnail size! https://bccampus.ca/files/2019/01/Symp-2019-1.jpg

**Comment by alex-418** [comment]
Related to #318
