### ISSUE TITLE
Breadcrumbs: best practice to avoid unwanted characters in breadcrums  

### ISSUE THREAD

**Issue by murphybarb** [BCcampus/bcc-sage#258]
## Submit a feature request or bug report

- [ ] This is a feature request
- [ X] This is a bug report
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/BCcampus/bcc-sage/issues)
- [ ] You cleared your Web Browsers cache to ensure all new styling and images were loaded. 

---

**What is the current behavior?**

Example page: https://helga.bccampus.ca/wp/bcc/event/symposium-2018-scholarly-teaching-learning-in-post-secondary-education-2/

In the breadcrumb trail on the above page, there are unwanted characters ("&#038;") that replace the use of "&" in the breadcrumb. 

This does not appear in the page title, which the breadcrumb is generated from. 

**What is the expected or desired behavior?**

Unwanted characters do not appear in breadcrumbs. 

## Feature Request

**Please provide use cases for changing the current behavior:**

X

**Other relevant information:**

What are the guidelines to avoid unwanted characters appearing in the breadcrumbs?

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/bcc-sage/commit/5aa38a9001b71e268e4c97f7a5bd010000866d8b and https://github.com/BCcampus/bcc-sage/commit/23cf02407f7a6312d33bdedd5029a043f84f1c64 

htmlentities `&#34;` are now decoded to their character output and since ampersands are behaving exceptionally `&amp;` replaced with the word `and` in the breadcrumb output as a work around.
