### ISSUE TITLE
megamenu regression with bootstrap >= 4.2

### ISSUE THREAD

**Issue by bdolor** [BCcampus/bcc-sage#312]
**Describe the bug**
mega menu functionality is lost when upgrading to the latest (4.2.1) of bootstrap

**To Reproduce**
1. update dep to 4.2.x
2. Click on Megamenu item
3. Open JS console
4. See error `not a valid selector`. Also dropdown menu won't function. 

**Expected behavior**
Megamenu dropdown should work with latest version of BS4

**Screenshots**
to avoid the bug, in the meantime, reverting to 4.1.3: https://github.com/BCcampus/bcc-sage/pull/310 

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox, Chrome

**Comment by alex-418** [comment]
This issue is [fixed](https://github.com/twbs/bootstrap/pull/27912) in next release [4.3](https://github.com/twbs/bootstrap/projects/16). Meanwhile that gets released ([soon](https://github.com/twbs/bootstrap/issues/27903#issuecomment-450334533)), I tried updating the code using the suggested [temporary fix](https://github.com/twbs/bootstrap/issues/27903#issuecomment-450292043) but it did not work in our case.

**Comment by alex-418** [comment]
We decided to wait for 4.3, no need to take any further action on this.
