### ISSUE TITLE
Update slider (smartslider plugin)

### ISSUE THREAD

**Issue by ehbeattie** [BCcampus/bcc-sage#349]
**Is your feature request related to a problem? Please describe.**
The slideshow isn't displaying/functioning as well as it could/should.

**Describe the solution you'd like**
Please match the mock-ups as much as possible.

**Describe alternatives you've considered**
-	This was intended to go full width, i would like you to look into the possibility of making it full width, with the blue overlay on 50%. But then still having the text content align to the contained grid.
-	The blue overlay needs to match the Topics and Projects overlays. No gradient!background: rgba(0,165,225,.75)
-	The headline needs to be using our font family:
font-family: ‘Helvetica Neue’, Helvetica, Arial, sans-serif;
-	The button needs to match the rest of the site, it needs to use our font family above and use these styles to match the mockup above:
background: #fff;
border-radius: 3px;
font-size: 15px;
line-height: 1.2;
font-weight: bold;
color: #000;
text-transform: uppercase;
padding: 10px 23px;
hover state: black background, white text

<img width="860" alt="Screen Shot 2019-05-27 at 2 52 46 PM" src="https://user-images.githubusercontent.com/44707412/58440479-1d31ea80-808f-11e9-975a-e823fa72b13f.png">

**Comment by stargraphicdesign** [comment]
slider styling has been updated. 

I added the css into the plugin settings, there's a spot for css overrides.

I have determined that it's not possible to go full width at this time with how the current site is programmed, it would require pulling it out of the page container.

Note, this plugin is coded in a way that if you add a new slide it may not inherit all of these css changes (this is why i never use plugins for slideshows anymore). you'll be better off just "updating" a slide rather than adding/removing
