### ISSUE TITLE
Change the time options for the events

### ISSUE THREAD

**Issue by ehbeattie** [BCcampus/bcc-sage#351]
**Is your feature request related to a problem? Please describe.**
We are getting stuck with the "all day" button option as it isn't accurate for courses that are asynchronous.

**Describe the solution you'd like**
Have another option for asynchronous and maybe an option to have it blank?

**Comment by alex-418** [comment]
@ehbeattie After researching this, the functionality is locked down by the plugin when it comes to adding a field for developers. The reason is they have a "pro" option at $149 that lets you add fields from the settings. However, in your description you said you'd like the option to "leave it blank"... this is possible when creating an event by selecting the "no end time" checkbox. Please let me know if this solves the problem:

![no-end](https://user-images.githubusercontent.com/17072191/58514641-5df53680-8157-11e9-8332-5269b7e68d86.png)

**Comment by ehbeattie** [comment]
Hi,

That's not an ideal option currently as it displays as 12:00 am 

Cheers,

Erin

**Comment by alex-418** [comment]
Thanks @ehbeattie, it's also possible to post an event without selecting "All Day" or "No end time", so you may choose the end time this way. The only thing missing would be the "asynchronous" badge beside the title. But we could tag it instead. Here's what that would look like. Let me know if this works for you:

![async](https://user-images.githubusercontent.com/17072191/58515710-8894be80-815a-11e9-9bfb-9ba91d7f0830.png)

**Comment by ehbeattie** [comment]
Ideally, no timeframe would be listed as it's confusing to create a time that isn't actually relevant.

**Comment by alex-418** [comment]
Decided during standup this will be a non-dev task, and events will be looked at overall to find a solution that meets our needs.
